version: "3.3"
services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped

  api:
    image: api-service
    depends_on:
      - redis 
    ports:
      - 8080:80
    environment:
      API_KEY: apikey
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SQLALCHEMY_DATABASE_URI: sqlite:////app/db/db.sqlite
